add retyr

diff --git a/blaster b/blaster
--- a/blaster
+++ b/blaster
@@ -80,9 +80,9 @@ create_request() {
 
     # catch unknown error preventing from receiving request id
     [ -z "$rid" ] && {
-        attachment="$(mktemp -p "$PWD" -t BLASTER-UNKNOWN-ERROR-XXXXXX.html)"
-        mv $reply $attachment
-        echo -e "\rError: something went wrong. Please, report to developer and attach this file: $attachment."
+        #attachment="$(mktemp -p "$PWD" -t BLASTER-UNKNOWN-ERROR-XXXXXX.html)"
+        #mv $reply $attachment
+        echo -e "\rError: something went wrong. Will retry."
         exit 1
     }
 
@@ -91,6 +91,7 @@ create_request() {
     # save request sequence for future searches
     mkdir -p blaster_requests/$rid
     mv $sequence blaster_requests/$rid/sequence.fasta
+    echo $filename > blaster_requests/$rid/filename
     rm $reply
 }
 
@@ -115,11 +116,7 @@ sync_reports() {
         printf "\r[$i / $count] $rid ..."
 
         # skip requests for which we already have reports
-        [ -f blaster_requests/$rid/report.csv -a -f blaster_requests/$rid/report.txt ] && {
-            # create tsv if missing
-            [ ! -f blaster_requests/$rid/report.tsv ] && cat blaster_requests/$rid/report.csv \
-                | sed -E 's/("([^"]*)")?,/\2\t/g;  s/"//g; s/=HYPERLINK.*\t(.*)\)/\1/;  s/\s*$//' \
-                | grep -v ^$ >blaster_requests/$rid/report.tsv
+        [ -f blaster_requests/$rid/report.csv ] && {
             ((old_matched_count++))
             continue
         }
@@ -138,6 +135,7 @@ sync_reports() {
 
         # get request page
         local reply=$(mktemp)
+        local response_csv=$(mktemp)
         curl -sSL "https://blast.ncbi.nlm.nih.gov/Blast.cgi?CMD=Get&RID=$rid" >$reply
 
         # request failed (creating a new request may help)
@@ -159,18 +157,21 @@ sync_reports() {
                 new_unmatched_rids+=($rid)
             } || {
                 # download report in csv format and generate tsv from it
-                curl -sSL "https://blast.ncbi.nlm.nih.gov/Blast.cgi?CMD=Get&RID=$rid&RESULTS_FILE=on&FORMAT_TYPE=CSV&DESCRIPTIONS=100&FORMAT_OBJECT=Alignment&QUERY_INDEX=0&DOWNLOAD_TEMPL=Results&ALIGNMENT_VIEW=Pairwise&QUERY_INDEX=0&CONFIG_DESCR=2,3,6,7,8,9,10,11,12" \
-                    | tee blaster_requests/$rid/report.csv \
-                    | sed -E 's/("([^"]*)")?,/\2\t/g;  s/"//g; s/=HYPERLINK.*\t(.*)\)/\1/;  s/\s*$//' \
-                    | grep -v ^$ >blaster_requests/$rid/report.tsv &
-                # download report in txt format
-                curl -sSL "https://blast.ncbi.nlm.nih.gov/Blast.cgi?CMD=Get&RID=$rid&RESULTS_FILE=on&FORMAT_TYPE=Text&DESCRIPTIONS=100&FORMAT_OBJECT=Alignment&QUERY_INDEX=0&DOWNLOAD_TEMPL=Results&ALIGNMENT_VIEW=Pairwise&QUERY_INDEX=0&CONFIG_DESCR=2,3,6,7,8,9,10,11,12" \
-                    >blaster_requests/$rid/report.txt &
+                while true
+                do
+                    curl -sSL "https://blast.ncbi.nlm.nih.gov/Blast.cgi?CMD=Get&RID=$rid&RESULTS_FILE=on&FORMAT_TYPE=CSV&DESCRIPTIONS=10&FORMAT_OBJECT=Alignment&QUERY_INDEX=0&DOWNLOAD_TEMPL=Results&ALIGNMENT_VIEW=Pairwise&QUERY_INDEX=0&CONFIG_DESCR=2,3,6,7,8,9,10,11,12" > $response_csv 2>/dev/null
+                    if [ $? -eq 0 ];then
+                        cat $response_csv > blaster_requests/$rid/report.csv
+                        break
+                    fi
+                    sleep 1
+                done
                 new_matched_rids+=($rid)
             }
         }
 
         rm $reply
+        rm $response_csv
     done
 
     local old_count=$[ $old_matched_count + $old_unmatched_count + $old_failed_count ]
@@ -186,19 +187,13 @@ sync_reports() {
     printf "ready:      %3d     %3d\n"  $old_count              $new_count
     printf "waiting:    %3d\n"          $waiting_count
 
-    
-    # [ ${#new_matched_rids[@]} -gt 0 ] && {
-    #     echo "new matched:"
-    #     (cd blaster_requests; ls -d "${new_matched_rids[*]}")
-    # }
-    # [ ${#new_unmatched_rids[@]} -gt 0 ] && {
-    #     echo "new unmatched:"
-    #     (cd blaster_requests; ls -d "${new_unmatched_rids[*]}")
-    # }
-    # [ ${#new_failed_rids[@]} -gt 0 ] && {
-    #     echo "new failed:"
-    #     (cd blaster_requests; ls -d "${new_failed_rids[*]}")
-    # }
+    ((total=$old_count+$new_count))
+    if [ $total -eq $count ]; then
+        exit 0
+    else
+        exit 1
+    fi
+
 }
 
 search_by_content() {
